mengxi-ream/read-frog

.changeset/flat-lamps-rescue.md, src/entrypoints/options/providers/base-url-config.tsx, src/entrypoints/options/providers/index.tsx, src/types/config/provider.ts, src/utils/config/__tests__/example/v5.ts, src/utils/config/__tests__/migration/v004-to-v005.test.ts, src/utils/config/migration.ts, src/utils/constants/config.ts, src/utils/provider.ts
- Allow users to configure a custom `Base URL`.
For #33
=> feat: add base URL configuration for providers

package.json, pnpm-lock.yaml, src/entrypoints/background/index.ts, src/entrypoints/background/translation.ts, src/entrypoints/host.content/index.tsx, src/entrypoints/host.content/translation-trigger/index.ts, src/entrypoints/host.content/translation-trigger/page-translation.ts, src/entrypoints/popup/components/translate-button.tsx, src/entrypoints/popup/main.tsx, src/entrypoints/side.content/atoms.ts, src/entrypoints/side.content/components/floating-button/translate-button.tsx, src/entrypoints/side.content/index.tsx, src/utils/host/translate-text.ts, src/utils/message.ts
=> fix: translate element when style or class has changes

src/entrypoints/background/new-user-guide.ts, src/entrypoints/background/translation.ts, src/entrypoints/guide.content/index.tsx, src/entrypoints/host.content/index.tsx, src/entrypoints/host.content/listen.ts, src/utils/config/config.ts, src/utils/constants/site.ts, src/utils/message.ts
=> fix: don't translate when change url

.changeset/gold-moles-jump.md, src/utils/host/dom/style.ts
fix: smash style in class by computed style
Closes #71
=> fix: smash style in class by computed style

.github/release.yml, .github/workflows/lint-pr.yml
=> ci: label pr in action for release

.changeset/violet-items-attend.md, .github/workflows/lint-pr.yml, README.md
=> docs(readme): add last commit

.changeset/odd-trees-begin.md, commitlint.config.cjs, src/entrypoints/host.content/listen.ts, src/entrypoints/side.content/components/floating-button/translate-button.tsx, src/utils/constants/translation.ts, src/utils/host/__test__/translate.test.tsx, src/utils/host/dom/filter.ts, src/utils/host/dom/traversal.ts, src/utils/host/translate.ts
…e in block-inline-mixed paragraph## Type of Changes
Closes #
=> fix(traversal): combine consecutive inline nodes to translate

.changeset/little-owls-work.md, src/utils/request/__test__/request-queue.test.ts, src/utils/request/request-queue.ts
=> feat: retry and timeout mechanism of request queue

.changeset/bright-carrots-invent.md, package.json, pnpm-lock.yaml, src/components/tranlation-error/error-button.tsx, src/components/tranlation-error/retry-button.tsx, src/components/ui/alert.tsx, src/components/ui/hover-card.tsx, src/components/ui/select.tsx, src/components/ui/tooltip.tsx, src/utils/react-shadow-host/shadow-host-builder.ts
=> style: update translation error button style

.changeset/shaggy-pumas-reply.md, .github/workflows/release.yml
=> ci: release multiple package

.changeset/calm-flowers-pay.md, apps/extension/src/entrypoints/guide.content/index.tsx, apps/extension/src/entrypoints/options/main.tsx, apps/extension/src/entrypoints/side.content/index.tsx, apps/extension/src/utils/atoms/storage-adapter.ts
=> fix: set target language right after entering guide step 1

.changeset/calm-friends-ring.md, .changeset/fast-carrots-sell.md, .gitignore, apps/extension/src/entrypoints/background/config.ts, apps/extension/src/entrypoints/host.content/index.tsx, apps/extension/src/entrypoints/host.content/translation-control/node-translation.ts, apps/extension/src/entrypoints/host.content/translation-control/page-translation.ts, apps/extension/src/entrypoints/host.content/translation-trigger/index.ts, apps/extension/src/utils/config/config.ts, apps/extension/src/utils/config/init.ts
=> refactor: translation control and fix load config

.changeset/yummy-dots-turn.md, apps/extension/src/entrypoints/options/pages/general/index.tsx, apps/extension/src/entrypoints/options/pages/general/reset-config.tsx, apps/extension/src/locales/en.yml, apps/extension/src/locales/ja.yml, apps/extension/src/locales/ko.yml, apps/extension/src/locales/zh-CN.yml, apps/extension/src/locales/zh-TW.yml
=> feat: reset config button

.changeset/brave-maps-rush.md, .changeset/tidy-readers-rule.md, .github/workflows/pr-test.yml, .husky/pre-push, apps/extension/src/entrypoints/selection.content/app.tsx, apps/extension/src/entrypoints/selection.content/index.tsx, apps/extension/src/entrypoints/side.content/index.tsx, apps/website/src/app/[locale]/layout.config.tsx, apps/website/src/app/[locale]/tutorial/[[...slug]]/page.tsx, apps/website/src/env.ts, apps/website/turbo.json
=> feat: add selection content

.changeset/brave-maps-rush.md, .changeset/forty-stars-remain.md, .changeset/tidy-readers-rule.md, .github/workflows/pr-test.yml, .husky/pre-push, apps/extension/src/entrypoints/background/request-queue.ts, apps/extension/src/entrypoints/options/components/field-with-label.tsx, apps/extension/src/entrypoints/options/pages/translation/index.tsx, apps/extension/src/entrypoints/options/pages/translation/request-rate.tsx, apps/extension/src/entrypoints/selection.content/index.tsx, apps/extension/src/entrypoints/side.content/index.tsx, apps/extension/src/locales/en.yml, apps/extension/src/locales/ja.yml, apps/extension/src/locales/ko.yml, apps/extension/src/locales/zh-CN.yml, apps/extension/src/locales/zh-TW.yml, apps/extension/src/types/config/provider.ts, apps/extension/src/utils/config/__tests__/example/v009.ts, apps/extension/src/utils/config/migration-scripts/v008-to-v009.ts, apps/extension/src/utils/constants/config.ts, apps/extension/src/utils/constants/translate.ts, apps/extension/src/utils/message.ts, apps/extension/src/utils/request/__test__/request-queue.test.ts, apps/extension/src/utils/request/request-queue.ts, apps/website/src/app/[locale]/layout.config.tsx, apps/website/src/app/[locale]/tutorial/[[...slug]]/page.tsx, apps/website/src/env.ts, apps/website/turbo.json
Expose translate request queue rate configuration in translate page
Closes #178
=> feat: implement expose translate request queue rate

.changeset/public-foxes-camp.md, .changeset/quiet-yaks-wonder.md, apps/extension/package.json, apps/extension/src/entrypoints/options/pages/translation/personalized-prompt.tsx, apps/extension/src/entrypoints/options/utils/prompt-file.ts, apps/extension/src/entrypoints/popup/components/translate-prompt-selector.tsx, apps/extension/src/entrypoints/selection.content/index.tsx, apps/extension/src/entrypoints/selection.content/selection-tooltip/index.tsx, apps/extension/src/entrypoints/selection.content/selection-tooltip/translate-button.tsx, apps/extension/src/types/config/provider.ts, apps/extension/src/utils/config/__tests__/example/v010.ts, apps/extension/src/utils/config/migration-scripts/v009-to-v010.ts, apps/extension/src/utils/constants/config.ts, apps/extension/src/utils/constants/prompt.ts, apps/extension/src/utils/host/translate/translate-text.ts, apps/extension/src/utils/prompts/translate.ts, apps/extension/src/utils/provider.ts, packages/eslint-config/base.js, pnpm-lock.yaml
Closes #
- [] Added unit tests
=> feat: translate selected content

apps/extension/package.json, apps/website/package.json, package.json, packages/db/package.json, packages/eslint-config/extension.js, packages/eslint-config/next.js, packages/eslint-config/package.json, pnpm-lock.yaml
=> build: update eslint config

apps/extension/package.json, apps/extension/src/utils/provider.ts, apps/website/package.json, apps/website/src/lib/constants.ts, packages/eslint-config/package.json, pnpm-lock.yaml
=> build: upgrade many packages

apps/website/package.json, package.json, turbo.json
=> chore: add dev edge script

.changeset/open-llamas-dream.md, apps/extension/src/utils/host/translate/node-manipulation.ts
=> fix: no error component after bilingual translation error

.changeset/easy-ads-mate.md, apps/extension/src/utils/config/__tests__/migration-scripts/all-migrations.test.ts
=> test: have to test every migration script

.changeset/light-carrots-serve.md, apps/extension/src/utils/config/__tests__/example/v022.ts, apps/extension/src/utils/config/__tests__/example/v023.ts, apps/extension/src/utils/config/__tests__/migration-scripts/all-migrations.test.ts, apps/extension/src/utils/config/migration-scripts/v022-to-v023.ts, apps/extension/src/utils/config/migration.ts
=> fix: static import migrations in service worker

.changeset/free-birds-double.md, apps/extension/src/components/provider/read-provider-selector.tsx, apps/extension/src/entrypoints/side.content/components/side-content/top-bar.tsx
=> fix: provider selector in side content

.changeset/itchy-wolves-stop.md, .changeset/tall-comics-leave.md, apps/extension/src/entrypoints/side.content/components/side-content/top-bar.tsx, apps/extension/src/hooks/read/read.tsx, apps/extension/src/utils/config/languages.ts, apps/extension/src/utils/constants/dom-tags.ts, apps/extension/src/utils/host/dom/filter.ts, apps/extension/src/utils/host/translate/auto-translation.ts, apps/extension/src/utils/host/translate/translate-text.ts
=> fix: hash key and translate code

.changeset/fancy-snakes-roll.md, .claude/commands/add-provider.md, apps/extension/package.json, apps/extension/src/locales/en.yml, apps/extension/src/locales/ja.yml, apps/extension/src/locales/ko.yml, apps/extension/src/locales/zh-CN.yml, apps/extension/src/locales/zh-TW.yml, apps/extension/src/types/config/provider.ts, apps/extension/src/utils/constants/providers.ts, apps/extension/src/utils/providers/model.ts, pnpm-lock.yaml
=> feat: add open router

.changeset/tidy-doors-flow.md, apps/extension/src/utils/host/__tests__/translate.integration.test.tsx, apps/extension/src/utils/host/dom/traversal.ts
=> fix: inline node with only one block child
